"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ar' | 'zh';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.features": "Features",
    "nav.solution": "Solution",
    "nav.pricing": "Pricing",
    "nav.blog": "Blog",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.getstarted": "Get Started",

    "hero.title": "One Platform to Run Your Sourcing & Logistics Business",
    "hero.subtitle": "From product sourcing to payment tracking — manage everything with your team and clients in one simple dashboard.",
    "hero.email_placeholder": "Enter your email",
    "hero.join_waitlist": "Join Waitlist",
    "hero.submitting": "Submitting...",
    "hero.success_message": "You're on the list! We'll notify you when we launch.",
    "hero.waitlist_note": "Be among the first to get early access",
    "hero.used_by": "Used by sourcing agents, trading companies, and warehouses worldwide.",

    "logocloud.title": "INTEGRATED WITH YOUR FAVORITE PLATFORMS",

    "blog.title": "Blog",
    "blog.subtitle": "Insights, tips, and guides for sourcing agents",

    "features.badge": "Everything you need",
    "features.title": "All-in-One Operations Platform",
    "features.subtitle": "Manage your entire sourcing lifecycle from a single, intuitive dashboard.",
    "features.card1.title": "Client Portal for Sourcing Agents",
    "features.card1.desc": "Give every client a clean dashboard to see their own quotations, orders, shipping, and payments.",
    "features.card1.bullet1": "Clients only see their data",
    "features.card1.bullet2": "Reduces daily status questions",
    "features.card1.bullet3": "Builds trust and professionalism",
    "features.card2.title": "Quotation Management",
    "features.card2.desc": "Create structured, clear quotes that help clients approve faster.",
    "features.card2.bullet1": "Cost breakdown + margin clarity",
    "features.card2.bullet2": "Reusable quote formats",
    "features.card2.bullet3": "Fewer misunderstandings",
    "features.card3.title": "Order Management Workflow",
    "features.card3.desc": "Turn approved quotations into trackable orders.",
    "features.card3.bullet1": "Clear order stages",
    "features.card3.bullet2": "Supplier + product history",
    "features.card3.bullet3": "Centralized documents and notes",
    "features.card4.title": "Shipping Tracking Updates",
    "features.card4.desc": "Keep clients informed with simple, reliable shipping status.",
    "features.card4.bullet1": "Manual stage updates (MVP-friendly)",
    "features.card4.bullet2": "Share tracking info cleanly",
    "features.card4.bullet3": "Less back-and-forth in WhatsApp",
    "features.card5.title": "Payment Tracking",
    "features.card5.desc": "Track deposits, balances, and payment steps per order.",
    "features.card5.bullet1": "Simple payment status logs",
    "features.card5.bullet2": "Clear client visibility",
    "features.card5.bullet3": "Reduces accounting confusion",
    "features.card6.title": "Product & Supplier Records",
    "features.card6.desc": "Build a reusable knowledge base for faster future sourcing.",
    "features.card6.bullet1": "Save product specs and images",
    "features.card6.bullet2": "Store supplier details",
    "features.card6.bullet3": "Improve speed for repeat clients",
    "features.card7.title": "Multi-Client Workspace",
    "features.card7.desc": "Manage many clients without mixing conversations or files.",
    "features.card7.bullet1": "Organized pipelines",
    "features.card7.bullet2": "Better follow-up discipline",
    "features.card7.bullet3": "Designed for solo agents and small teams",
    "features.card8.title": "Agency Website / Landing Builder (Pro)",
    "features.card8.desc": "Present your agency professionally and capture inbound leads.",
    "features.card8.bullet1": "Simple website blocks",
    "features.card8.bullet2": "Brand-ready presentation",
    "features.card8.bullet3": "Connect leads to your portal workflow",

    "solution.title": "Life After SourSync",
    "solution.text_rotate": "Simplified,Streamlined,Success-Driven",
    "solution.before.title": "The Struggle",
    "solution.before.item1": "Too many apps & tools",
    "solution.before.item2": "Time-consuming manual quotations",
    "solution.before.item3": "Communication chaos (WeChat, WhatsApp)",
    "solution.before.item4": "Errors in spreadsheets & data loss",
    "solution.after.title": "The Solution",
    "solution.after.item1": "All-in-one sourcing dashboard",
    "solution.after.item2": "Instant quotation builder",
    "solution.after.item3": "Real-time tracking for clients and orders",
    "solution.after.item4": "Integrated communication hub",

    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Choose the plan that fits your needs.",
    "pricing.monthly": "monthly",
    "pricing.yearly": "yearly",
    "pricing.compare_title": "Compare Plans",
    "pricing.compare_subtitle": "Detailed feature comparison",
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.desc": "Best for new or solo agents who want a professional system instead of WhatsApp + Excel.",
    "pricing.plan.starter.cta": "Join Waitlist",
    "pricing.plan.growth.name": "Growth",
    "pricing.plan.growth.desc": "Best for active agents managing more clients and frequent shipments.",
    "pricing.plan.growth.cta": "Join Waitlist",
    "pricing.plan.pro.name": "Pro",
    "pricing.plan.pro.desc": "Best for agencies that want a stronger brand experience and scalable operations.",
    "pricing.plan.pro.cta": "Join Waitlist",
    "pricing.table.feature": "Feature",
    "pricing.table.starter": "Starter",
    "pricing.table.pro": "Pro",
    "pricing.table.agency": "Agency",
    "pricing.table.enterprise": "Enterprise",

    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Everything you need to know about SourSync.",
    "faq.q1": "What is SourSync?",
    "faq.a1": "SourSync is an all-in-one sourcing agent software that helps you manage client inquiries, product sourcing, quotations, orders, shipping, and payments in one system with a professional client portal.",
    "faq.q2": "Who should use SourSync?",
    "faq.a2": "SourSync is built for China sourcing agents, import/export agents, trading offices, and small teams that want to replace WhatsApp + Excel with a structured dashboard and a client-facing portal.",
    "faq.q3": "How does SourSync help sourcing agents?",
    "faq.a3": "SourSync reduces back-and-forth by centralizing quotation management, order status updates, shipping tracking, payment tracking, and client communication history. This improves trust, speeds decisions, and helps you close more deals.",
    "faq.q4": "Does SourSync include a client portal?",
    "faq.a4": "Yes. Each client gets a secure login to a client portal for sourcing agents where they can view quotations, order progress, shipping updates, and payment status.",
    "faq.q5": "Can clients approve quotations inside SourSync?",
    "faq.a5": "Yes. SourSync supports a clean quotation workflow where clients can review and confirm quotes, reducing delays and misunderstandings.",
    "faq.q6": "Is SourSync good for solo sourcing agents?",
    "faq.a6": "Yes. SourSync is designed for solo founders and small agencies who want a simple setup and a professional system that looks like a larger operation.",
    "faq.q7": "Can I manage multiple clients and orders at the same time?",
    "faq.a7": "Yes. SourSync is made for multi-client operations, allowing you to track multiple quotations, orders, and shipments without mixing data.",
    "faq.q8": "Does SourSync support order management?",
    "faq.a8": "Yes. SourSync functions as an order management system for sourcing agents, letting you track order stages, supplier details, timelines, and client updates in one place.",
    "faq.q9": "Does SourSync provide shipping tracking?",
    "faq.a9": "Yes. You can update shipping stages and share tracking info, making SourSync a practical shipping tracking tool for import/export workflows.",
    "faq.q10": "Can I track payments and balances?",
    "faq.a10": "Yes. SourSync provides structured payment tracking for sourcing agents, so you can log deposits, remaining balances, and payment milestones per order.",
    "faq.q11": "Can SourSync replace WhatsApp?",
    "faq.a11": "SourSync does not force you to stop using WhatsApp. Instead, it becomes your official system for quotations, orders, shipping, and payments, while WhatsApp remains a communication channel.",
    "faq.q12": "Does SourSync offer a website or landing page builder for agents?",
    "faq.a12": "Yes. SourSync can include a simple website/landing page builder for sourcing agencies, allowing you to present your services, capture leads, and connect clients to your portal.",
    "faq.q13": "Can I use my own domain with SourSync?",
    "faq.a13": "Yes. With supported plans, you can connect a custom domain for your agency website and client portal to strengthen your brand credibility.",
    "faq.q14": "Is my client data secure?",
    "faq.a14": "Yes. SourSync uses modern authentication and access control so each client only sees their own data, supporting a secure multi-client SaaS workflow.",
    "faq.q15": "How fast can I start using SourSync?",
    "faq.a15": "Most agents can set up their workspace and begin sharing quotations and client access quickly, often within the same day.",
    "faq.q16": "What payment methods do you accept?",
    "faq.a16": "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, and bank transfers for Enterprise plans.",
    "faq.more_questions": "Still have questions?",
    "faq.contact_support": "Contact Support",

    "footer.rights": "All rights reserved.",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "cta.title": "Ready to streamline your sourcing business?",
    "cta.subtitle": "Join the waitlist to be among the first to access SourSync when we launch.",
    "cta.email_placeholder": "Enter your email",
    "cta.join_waitlist": "Join Waitlist",
    "cta.submitting": "Submitting...",
    "cta.success_message": "You're on the list! We'll notify you when we launch.",
    "cta.note": "Early access • Priority support • Exclusive updates",
  },
  fr: {
    "nav.features": "Fonctionnalités",
    "nav.solution": "Solution",
    "nav.pricing": "Tarification",
    "nav.blog": "Blog",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.login": "Connexion",
    "nav.signup": "S'inscrire",
    "nav.getstarted": "Commencer",

    "hero.title": "Une plateforme unique pour gérer votre activité de sourcing et de logistique",
    "hero.subtitle": "Du sourcing produit au suivi des paiements — gérez tout avec votre équipe et vos clients dans un tableau de bord simple.",
    "hero.email_placeholder": "Entrez votre email",
    "hero.join_waitlist": "Rejoindre la liste",
    "hero.submitting": "Envoi en cours...",
    "hero.success_message": "Vous êtes sur la liste ! Nous vous notifierons lors du lancement.",
    "hero.waitlist_note": "Soyez parmi les premiers à obtenir un accès anticipé",
    "hero.used_by": "Utilisé par des agents de sourcing, des sociétés de négoce et des entrepôts dans le monde entier.",

    "logocloud.title": "INTÉGRÉ AVEC VOS PLATEFORMES PRÉFÉRÉES",

    "blog.title": "Blog",
    "blog.subtitle": "Conseils, astuces et guides pour les agents de sourcing",

    "features.badge": "Tout ce dont vous avez besoin",
    "features.title": "Plateforme d'opérations tout-en-un",
    "features.subtitle": "Gérez l'ensemble de votre cycle de sourcing depuis un tableau de bord unique et intuitif.",
    "features.card1.title": "Portail Client pour Agents de Sourcing",
    "features.card1.desc": "Offrez à chaque client un tableau de bord propre pour voir ses propres devis, commandes, expéditions et paiements.",
    "features.card1.bullet1": "Les clients ne voient que leurs données",
    "features.card1.bullet2": "Réduit les questions quotidiennes sur le statut",
    "features.card1.bullet3": "Renforce la confiance et le professionnalisme",
    "features.card2.title": "Gestion des Devis",
    "features.card2.desc": "Créez des devis structurés et clairs qui aident les clients à approuver plus rapidement.",
    "features.card2.bullet1": "Détail des coûts + clarté des marges",
    "features.card2.bullet2": "Formats de devis réutilisables",
    "features.card2.bullet3": "Moins de malentendus",
    "features.card3.title": "Workflow de Gestion des Commandes",
    "features.card3.desc": "Transformez les devis approuvés en commandes traçables.",
    "features.card3.bullet1": "Étapes de commande claires",
    "features.card3.bullet2": "Historique fournisseur + produit",
    "features.card3.bullet3": "Documents et notes centralisés",
    "features.card4.title": "Mises à Jour de Suivi d'Expédition",
    "features.card4.desc": "Tenez les clients informés avec un statut d'expédition simple et fiable.",
    "features.card4.bullet1": "Mises à jour manuelles des étapes (compatible MVP)",
    "features.card4.bullet2": "Partagez les informations de suivi proprement",
    "features.card4.bullet3": "Moins d'allers-retours dans WhatsApp",
    "features.card5.title": "Suivi des Paiements",
    "features.card5.desc": "Suivez les acomptes, soldes et étapes de paiement par commande.",
    "features.card5.bullet1": "Journaux de statut de paiement simples",
    "features.card5.bullet2": "Visibilité client claire",
    "features.card5.bullet3": "Réduit la confusion comptable",
    "features.card6.title": "Enregistrements Produits & Fournisseurs",
    "features.card6.desc": "Construisez une base de connaissances réutilisable pour un sourcing futur plus rapide.",
    "features.card6.bullet1": "Enregistrez les spécifications et images de produits",
    "features.card6.bullet2": "Stockez les détails des fournisseurs",
    "features.card6.bullet3": "Améliorez la vitesse pour les clients récurrents",
    "features.card7.title": "Espace de Travail Multi-Clients",
    "features.card7.desc": "Gérez de nombreux clients sans mélanger les conversations ou fichiers.",
    "features.card7.bullet1": "Pipelines organisés",
    "features.card7.bullet2": "Meilleure discipline de suivi",
    "features.card7.bullet3": "Conçu pour les agents solo et petites équipes",
    "features.card8.title": "Constructeur de Site Web / Landing Page d'Agence (Pro)",
    "features.card8.desc": "Présentez votre agence professionnellement et capturez les leads entrants.",
    "features.card8.bullet1": "Blocs de site web simples",
    "features.card8.bullet2": "Présentation prête pour la marque",
    "features.card8.bullet3": "Connectez les leads à votre workflow de portail",

    "solution.title": "La vie après SourSync",
    "solution.text_rotate": "Simplifiée,Optimisée,Axée sur le succès",
    "solution.before.title": "La Lutte",
    "solution.before.item1": "Trop d'applications et d'outils",
    "solution.before.item2": "Devis manuels chronophages",
    "solution.before.item3": "Chaos de communication (WeChat, WhatsApp)",
    "solution.before.item4": "Erreurs dans les tableurs et perte de données",
    "solution.after.title": "La Solution",
    "solution.after.item1": "Tableau de bord de sourcing tout-en-un",
    "solution.after.item2": "Générateur de devis instantané",
    "solution.after.item3": "Suivi en temps réel pour clients et commandes",
    "solution.after.item4": "Hub de communication intégré",

    "pricing.title": "Tarification Simple et Transparente",
    "pricing.subtitle": "Choisissez le plan qui correspond à vos besoins.",
    "pricing.monthly": "mensuel",
    "pricing.yearly": "annuel",
    "pricing.compare_title": "Comparer les Plans",
    "pricing.compare_subtitle": "Comparaison détaillée des fonctionnalités",
    "pricing.plan.starter.name": "Starter",
    "pricing.plan.starter.desc": "Pour agents solo, freelances, débutants.",
    "pricing.plan.starter.cta": "Rejoindre la liste",
    "pricing.plan.growth.name": "Croissance",
    "pricing.plan.growth.desc": "Idéal pour les agents actifs gérant plus de clients et d'expéditions fréquentes.",
    "pricing.plan.growth.cta": "Rejoindre la liste",
    "pricing.plan.pro.name": "Pro",
    "pricing.plan.pro.desc": "Idéal pour les agences qui souhaitent une expérience de marque plus forte et des opérations évolutives.",
    "pricing.plan.pro.cta": "Rejoindre la liste",
    "pricing.table.feature": "Fonctionnalité",
    "pricing.table.starter": "Starter",
    "pricing.table.pro": "Pro",
    "pricing.table.agency": "Agence",
    "pricing.table.enterprise": "Entreprise",

    "faq.title": "Questions Fréquemment Posées",
    "faq.subtitle": "Tout ce que vous devez savoir sur SourSync.",
    "faq.q1": "Qu'est-ce que SourSync ?",
    "faq.a1": "SourSync est un logiciel tout-en-un pour agents de sourcing qui vous aide à gérer les demandes clients, le sourcing de produits, les devis, les commandes, l'expédition et les paiements dans un seul système avec un portail client professionnel.",
    "faq.q2": "Qui devrait utiliser SourSync ?",
    "faq.a2": "SourSync est conçu pour les agents de sourcing en Chine, les agents d'import/export, les bureaux de négoce et les petites équipes qui souhaitent remplacer WhatsApp + Excel par un tableau de bord structuré et un portail client.",
    "faq.q3": "Comment SourSync aide-t-il les agents de sourcing ?",
    "faq.a3": "SourSync réduit les allers-retours en centralisant la gestion des devis, les mises à jour de statut des commandes, le suivi des expéditions, le suivi des paiements et l'historique de communication client. Cela améliore la confiance, accélère les décisions et vous aide à conclure plus d'affaires.",
    "faq.q4": "SourSync inclut-il un portail client ?",
    "faq.a4": "Oui. Chaque client obtient une connexion sécurisée à un portail client pour agents de sourcing où il peut consulter les devis, l'avancement des commandes, les mises à jour d'expédition et le statut des paiements.",
    "faq.q5": "Les clients peuvent-ils approuver les devis dans SourSync ?",
    "faq.a5": "Oui. SourSync prend en charge un workflow de devis clair où les clients peuvent examiner et confirmer les devis, réduisant les retards et les malentendus.",
    "faq.q6": "SourSync est-il adapté aux agents de sourcing solo ?",
    "faq.a6": "Oui. SourSync est conçu pour les fondateurs solo et les petites agences qui souhaitent une configuration simple et un système professionnel qui ressemble à une opération plus importante.",
    "faq.q7": "Puis-je gérer plusieurs clients et commandes en même temps ?",
    "faq.a7": "Oui. SourSync est conçu pour les opérations multi-clients, vous permettant de suivre plusieurs devis, commandes et expéditions sans mélanger les données.",
    "faq.q8": "SourSync prend-il en charge la gestion des commandes ?",
    "faq.a8": "Oui. SourSync fonctionne comme un système de gestion des commandes pour agents de sourcing, vous permettant de suivre les étapes des commandes, les détails des fournisseurs, les délais et les mises à jour clients en un seul endroit.",
    "faq.q9": "SourSync fournit-il un suivi d'expédition ?",
    "faq.a9": "Oui. Vous pouvez mettre à jour les étapes d'expédition et partager les informations de suivi, faisant de SourSync un outil pratique de suivi d'expédition pour les workflows d'import/export.",
    "faq.q10": "Puis-je suivre les paiements et les soldes ?",
    "faq.a10": "Oui. SourSync fournit un suivi structuré des paiements pour les agents de sourcing, vous permettant d'enregistrer les acomptes, les soldes restants et les jalons de paiement par commande.",
    "faq.q11": "SourSync peut-il remplacer WhatsApp ?",
    "faq.a11": "SourSync ne vous force pas à arrêter d'utiliser WhatsApp. Au lieu de cela, il devient votre système officiel pour les devis, les commandes, l'expédition et les paiements, tandis que WhatsApp reste un canal de communication.",
    "faq.q12": "SourSync offre-t-il un constructeur de site web ou de page d'atterrissage pour les agents ?",
    "faq.a12": "Oui. SourSync peut inclure un constructeur de site web/page d'atterrissage simple pour les agences de sourcing, vous permettant de présenter vos services, de capturer des leads et de connecter les clients à votre portail.",
    "faq.q13": "Puis-je utiliser mon propre domaine avec SourSync ?",
    "faq.a13": "Oui. Avec les plans pris en charge, vous pouvez connecter un domaine personnalisé pour le site web de votre agence et le portail client pour renforcer la crédibilité de votre marque.",
    "faq.q14": "Mes données client sont-elles sécurisées ?",
    "faq.a14": "Oui. SourSync utilise une authentification moderne et un contrôle d'accès pour que chaque client ne voie que ses propres données, supportant un workflow SaaS multi-clients sécurisé.",
    "faq.q15": "À quelle vitesse puis-je commencer à utiliser SourSync ?",
    "faq.a15": "La plupart des agents peuvent configurer leur espace de travail et commencer à partager des devis et l'accès client rapidement, souvent le même jour.",
    "faq.q16": "Quels modes de paiement acceptez-vous ?",
    "faq.a16": "Nous acceptons toutes les principales cartes de crédit, PayPal et les virements bancaires pour les plans Entreprise.",
    "faq.more_questions": "Encore des questions ?",
    "faq.contact_support": "Contacter le Support",

    "footer.rights": "Tous droits réservés.",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    "cta.title": "Prêt à rationaliser votre activité de sourcing ?",
    "cta.subtitle": "Rejoignez la liste d'attente pour être parmi les premiers à accéder à SourSync lors du lancement.",
    "cta.email_placeholder": "Entrez votre email",
    "cta.join_waitlist": "Rejoindre la liste",
    "cta.submitting": "Envoi en cours...",
    "cta.success_message": "Vous êtes sur la liste ! Nous vous notifierons lors du lancement.",
    "cta.note": "Accès anticipé • Support prioritaire • Mises à jour exclusives",
  },
  ar: {
    "nav.features": "المميزات",
    "nav.solution": "الحل",
    "nav.pricing": "الأسعار",
    "nav.blog": "المدونة",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "انشاء حساب",
    "nav.getstarted": "ابدأ الآن",

    "hero.title": "منصة واحدة لإدارة أعمال التوريد والخدمات اللوجستية الخاصة بك",
    "hero.subtitle": "من مصادر المنتجات إلى تتبع المدفوعات - قم بإدارة كل شيء مع فريقك وعملائك في لوحة تحكم واحدة بسيطة.",
    "hero.email_placeholder": "أدخل بريدك الإلكتروني",
    "hero.join_waitlist": "انضم إلى القائمة",
    "hero.submitting": "جاري الإرسال...",
    "hero.success_message": "أنت في القائمة! سنخطرك عند الإطلاق.",
    "hero.waitlist_note": "كن من بين الأوائل للحصول على وصول مبكر",
    "hero.used_by": "يستخدمه وكلاء التوريد والشركات التجارية والمستودعات في جميع أنحاء العالم.",

    "logocloud.title": "متكامل مع منصاتك المفضلة",

    "blog.title": "المدونة",
    "blog.subtitle": "رؤى ونصائح ودلائل لوكلاء التوريد",

    "features.badge": "كل ما تحتاجه",
    "features.title": "منصة عمليات متكاملة",
    "features.subtitle": "أدر دورة حياة التوريد بالكامل من لوحة تحكم واحدة بديهية.",
    "features.card1.title": "بوابة العملاء لوكلاء التوريد",
    "features.card1.desc": "امنح كل عميل لوحة تحكم نظيفة لرؤية عروضه وطلباته وشحناته ومدفوعاته.",
    "features.card1.bullet1": "العملاء يرون بياناتهم فقط",
    "features.card1.bullet2": "يقلل من أسئلة الحالة اليومية",
    "features.card1.bullet3": "يبني الثقة والاحترافية",
    "features.card2.title": "إدارة العروض",
    "features.card2.desc": "أنشئ عروض منظمة وواضحة تساعد العملاء على الموافقة بشكل أسرع.",
    "features.card2.bullet1": "تفصيل التكلفة + وضوح الهامش",
    "features.card2.bullet2": "تنسيقات عروض قابلة لإعادة الاستخدام",
    "features.card2.bullet3": "تقليل سوء الفهم",
    "features.card3.title": "سير عمل إدارة الطلبات",
    "features.card3.desc": "حول العروض المعتمدة إلى طلبات قابلة للتتبع.",
    "features.card3.bullet1": "مراحل طلب واضحة",
    "features.card3.bullet2": "تاريخ المورد + المنتج",
    "features.card3.bullet3": "وثائق وملاحظات مركزية",
    "features.card4.title": "تحديثات تتبع الشحن",
    "features.card4.desc": "أبقِ العملاء على اطلاع بحالة شحن بسيطة وموثوقة.",
    "features.card4.bullet1": "تحديثات يدوية للمراحل (متوافق مع MVP)",
    "features.card4.bullet2": "شارك معلومات التتبع بشكل نظيف",
    "features.card4.bullet3": "تقليل المراسلات في WhatsApp",
    "features.card5.title": "تتبع المدفوعات",
    "features.card5.desc": "تتبع الودائع والأرصدة وخطوات الدفع لكل طلب.",
    "features.card5.bullet1": "سجلات حالة دفع بسيطة",
    "features.card5.bullet2": "وضوح رؤية العميل",
    "features.card5.bullet3": "يقلل من الارتباك المحاسبي",
    "features.card6.title": "سجلات المنتجات والموردين",
    "features.card6.desc": "أنشئ قاعدة معرفة قابلة لإعادة الاستخدام لتوريد أسرع في المستقبل.",
    "features.card6.bullet1": "احفظ مواصفات وصور المنتجات",
    "features.card6.bullet2": "خزن تفاصيل الموردين",
    "features.card6.bullet3": "حسّن السرعة للعملاء المتكررين",
    "features.card7.title": "مساحة عمل متعددة العملاء",
    "features.card7.desc": "أدر العديد من العملاء دون خلط المحادثات أو الملفات.",
    "features.card7.bullet1": "خطوط أنابيب منظمة",
    "features.card7.bullet2": "انضباط متابعة أفضل",
    "features.card7.bullet3": "مصمم للوكلاء الأفراد والفرق الصغيرة",
    "features.card8.title": "منشئ موقع الوكالة / صفحة الهبوط (Pro)",
    "features.card8.desc": "اعرض وكالتك بشكل احترافي واجذب العملاء المحتملين.",
    "features.card8.bullet1": "كتل موقع ويب بسيطة",
    "features.card8.bullet2": "عرض جاهز للعلامة التجارية",
    "features.card8.bullet3": "اربط العملاء المحتملين بسير عمل البوابة",

    "solution.title": "الحياة بعد SourSync",
    "solution.text_rotate": "مبسطة,انسيابية,موجهة نحو النجاح",
    "solution.before.title": "المعاناة",
    "solution.before.item1": "تطبيقات وأدوات كثيرة جدًا",
    "solution.before.item2": "عروض أسعار يدوية تستغرق وقتًا طويلاً",
    "solution.before.item3": "فوضى الاتصال (WeChat, WhatsApp)",
    "solution.before.item4": "أخطاء في جداول البيانات وفقدان للبيانات",
    "solution.after.title": "الحل",
    "solution.after.item1": "لوحة تحكم توريد شاملة",
    "solution.after.item2": "منشئ عروض أسعار فوري",
    "solution.after.item3": "تتبع في الوقت الفعلي للعملاء والطلبات",
    "solution.after.item4": "مركز اتصال متكامل",

    "pricing.title": "تسعير بسيط وشفاف",
    "pricing.subtitle": "اختر الخطة التي تناسب احتياجاتك.",
    "pricing.monthly": "شهري",
    "pricing.yearly": "سنوي",
    "pricing.compare_title": "مقارنة الخطط",
    "pricing.compare_subtitle": "مقارنة مفصلة للميزات",
    "pricing.plan.starter.name": "مبتدئ",
    "pricing.plan.starter.desc": "للوكلاء الأفراد، المستقلين، المبتدئين.",
    "pricing.plan.starter.cta": "انضم إلى القائمة",
    "pricing.plan.growth.name": "النمو",
    "pricing.plan.growth.desc": "الأفضل للوكلاء النشطين الذين يديرون المزيد من العملاء والشحنات المتكررة.",
    "pricing.plan.growth.cta": "انضم إلى القائمة",
    "pricing.plan.pro.name": "محترف",
    "pricing.plan.pro.desc": "الأفضل للوكالات التي تريد تجربة علامة تجارية أقوى وعمليات قابلة للتوسع.",
    "pricing.plan.pro.cta": "انضم إلى القائمة",
    "pricing.table.feature": "الميزة",
    "pricing.table.starter": "مبتدئ",
    "pricing.table.pro": "محترف",
    "pricing.table.agency": "وكالة",
    "pricing.table.enterprise": "مؤسسة",

    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "كل ما تحتاج معرفته حول SourSync.",
    "faq.q1": "ما هو SourSync؟",
    "faq.a1": "SourSync هو برنامج شامل لوكلاء التوريد يساعدك على إدارة استفسارات العملاء وتوريد المنتجات والعروض والطلبات والشحن والمدفوعات في نظام واحد مع بوابة عملاء احترافية.",
    "faq.q2": "من يجب أن يستخدم SourSync؟",
    "faq.a2": "تم بناء SourSync لوكلاء التوريد في الصين ووكلاء الاستيراد/التصدير ومكاتب التجارة والفرق الصغيرة التي تريد استبدال WhatsApp + Excel بلوحة تحكم منظمة وبوابة موجهة للعملاء.",
    "faq.q3": "كيف يساعد SourSync وكلاء التوريد؟",
    "faq.a3": "يقلل SourSync من المراسلات المتكررة من خلال مركزة إدارة العروض وتحديثات حالة الطلبات وتتبع الشحن وتتبع المدفوعات وسجل اتصالات العملاء. هذا يحسن الثقة ويسرع القرارات ويساعدك على إغلاق المزيد من الصفقات.",
    "faq.q4": "هل يتضمن SourSync بوابة عملاء؟",
    "faq.a4": "نعم. يحصل كل عميل على تسجيل دخول آمن إلى بوابة عملاء لوكلاء التوريد حيث يمكنه عرض العروض وتقدم الطلبات وتحديثات الشحن وحالة الدفع.",
    "faq.q5": "هل يمكن للعملاء الموافقة على العروض داخل SourSync؟",
    "faq.a5": "نعم. يدعم SourSync سير عمل عروض نظيف حيث يمكن للعملاء مراجعة وتأكيد العروض، مما يقلل من التأخيرات وسوء الفهم.",
    "faq.q6": "هل SourSync جيد لوكلاء التوريد الأفراد؟",
    "faq.a6": "نعم. تم تصميم SourSync للمؤسسين الأفراد والوكالات الصغيرة الذين يريدون إعدادًا بسيطًا ونظامًا احترافيًا يبدو وكأنه عملية أكبر.",
    "faq.q7": "هل يمكنني إدارة عدة عملاء وطلبات في نفس الوقت؟",
    "faq.a7": "نعم. تم تصميم SourSync للعمليات متعددة العملاء، مما يسمح لك بتتبع عدة عروض وطلبات وشحنات دون خلط البيانات.",
    "faq.q8": "هل يدعم SourSync إدارة الطلبات؟",
    "faq.a8": "نعم. يعمل SourSync كنظام إدارة طلبات لوكلاء التوريد، مما يتيح لك تتبع مراحل الطلب وتفاصيل الموردين والجداول الزمنية وتحديثات العملاء في مكان واحد.",
    "faq.q9": "هل يوفر SourSync تتبع الشحن؟",
    "faq.a9": "نعم. يمكنك تحديث مراحل الشحن ومشاركة معلومات التتبع، مما يجعل SourSync أداة عملية لتتبع الشحن لسير عمل الاستيراد/التصدير.",
    "faq.q10": "هل يمكنني تتبع المدفوعات والأرصدة؟",
    "faq.a10": "نعم. يوفر SourSync تتبعًا منظمًا للمدفوعات لوكلاء التوريد، حتى تتمكن من تسجيل الودائع والأرصدة المتبقية ومعالم الدفع لكل طلب.",
    "faq.q11": "هل يمكن لـ SourSync استبدال WhatsApp؟",
    "faq.a11": "لا يجبرك SourSync على التوقف عن استخدام WhatsApp. بدلاً من ذلك، يصبح نظامك الرسمي للعروض والطلبات والشحن والمدفوعات، بينما يبقى WhatsApp قناة اتصال.",
    "faq.q12": "هل يقدم SourSync منشئ موقع ويب أو صفحة هبوط للوكلاء؟",
    "faq.a12": "نعم. يمكن أن يتضمن SourSync منشئ موقع ويب/صفحة هبوط بسيط لوكالات التوريد، مما يسمح لك بعرض خدماتك وجذب العملاء المحتملين وربط العملاء ببوابتك.",
    "faq.q13": "هل يمكنني استخدام نطاقي الخاص مع SourSync؟",
    "faq.a13": "نعم. مع الخطط المدعومة، يمكنك ربط نطاق مخصص لموقع وكالتك وبوابة العملاء لتعزيز مصداقية علامتك التجارية.",
    "faq.q14": "هل بيانات عميلي آمنة؟",
    "faq.a14": "نعم. يستخدم SourSync المصادقة الحديثة والتحكم في الوصول بحيث يرى كل عميل بياناته فقط، مما يدعم سير عمل SaaS متعدد العملاء آمن.",
    "faq.q15": "ما مدى سرعة بدء استخدام SourSync؟",
    "faq.a15": "يمكن لمعظم الوكلاء إعداد مساحة عملهم والبدء في مشاركة العروض والوصول للعملاء بسرعة، غالبًا في نفس اليوم.",
    "faq.q16": "ما هي طرق الدفع المقبولة؟",
    "faq.a16": "نقبل جميع بطاقات الائتمان الرئيسية و PayPal والتحويلات البنكية للخطط المؤسسية.",
    "faq.more_questions": "لا تزال لديك أسئلة؟",
    "faq.contact_support": "اتصل بالدعم",

    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.terms": "شروط الخدمة",
    "footer.privacy": "سياسة الخصوصية",
    "cta.title": "جاهز لتبسيط أعمال التوريد الخاصة بك؟",
    "cta.subtitle": "انضم إلى قائمة الانتظار لتكون من بين الأوائل للوصول إلى SourSync عند الإطلاق.",
    "cta.email_placeholder": "أدخل بريدك الإلكتروني",
    "cta.join_waitlist": "انضم إلى القائمة",
    "cta.submitting": "جاري الإرسال...",
    "cta.success_message": "أنت في القائمة! سنخطرك عند الإطلاق.",
    "cta.note": "وصول مبكر • دعم ذو أولوية • تحديثات حصرية",
  },
  zh: {
    "nav.features": "功能",
    "nav.solution": "解决方案",
    "nav.pricing": "定价",
    "nav.blog": "博客",
    "nav.about": "关于我们",
    "nav.contact": "联系我们",
    "nav.login": "登录",
    "nav.signup": "注册",
    "nav.getstarted": "立即开始",

    "hero.title": "一个平台管理您的采购和物流业务",
    "hero.subtitle": "从产品采购到付款跟踪 —— 在一个简单的仪表板中管理团队和客户的所有事务。",
    "hero.email_placeholder": "输入您的邮箱",
    "hero.join_waitlist": "加入候补名单",
    "hero.submitting": "提交中...",
    "hero.success_message": "您已加入列表！我们将在发布时通知您。",
    "hero.waitlist_note": "成为首批获得早期访问权限的用户",
    "hero.used_by": "被全球采购代理、贸易公司和仓库使用。",

    "logocloud.title": "与您喜爱的平台集成",

    "blog.title": "博客",
    "blog.subtitle": "采购代理的见解、技巧和指南",

    "features.badge": "您需要的一切",
    "features.title": "一体化运营平台",
    "features.subtitle": "通过一个直观的仪表板管理您的整个采购生命周期。",
    "features.card1.title": "采购代理客户门户",
    "features.card1.desc": "为每个客户提供清晰的仪表板，查看他们自己的报价、订单、运输和付款。",
    "features.card1.bullet1": "客户只能看到自己的数据",
    "features.card1.bullet2": "减少日常状态询问",
    "features.card1.bullet3": "建立信任和专业性",
    "features.card2.title": "报价管理",
    "features.card2.desc": "创建结构化、清晰的报价，帮助客户更快批准。",
    "features.card2.bullet1": "成本明细 + 利润率清晰",
    "features.card2.bullet2": "可重复使用的报价格式",
    "features.card2.bullet3": "减少误解",
    "features.card3.title": "订单管理工作流程",
    "features.card3.desc": "将已批准的报价转换为可跟踪的订单。",
    "features.card3.bullet1": "清晰的订单阶段",
    "features.card3.bullet2": "供应商 + 产品历史",
    "features.card3.bullet3": "集中式文档和备注",
    "features.card4.title": "运输跟踪更新",
    "features.card4.desc": "通过简单可靠的运输状态让客户了解情况。",
    "features.card4.bullet1": "手动阶段更新（MVP友好）",
    "features.card4.bullet2": "清晰地分享跟踪信息",
    "features.card4.bullet3": "减少在WhatsApp中的来回沟通",
    "features.card5.title": "付款跟踪",
    "features.card5.desc": "跟踪每笔订单的押金、余额和付款步骤。",
    "features.card5.bullet1": "简单的付款状态日志",
    "features.card5.bullet2": "清晰的客户可见性",
    "features.card5.bullet3": "减少会计混乱",
    "features.card6.title": "产品和供应商记录",
    "features.card6.desc": "构建可重复使用的知识库，加快未来采购速度。",
    "features.card6.bullet1": "保存产品规格和图片",
    "features.card6.bullet2": "存储供应商详情",
    "features.card6.bullet3": "提高重复客户的速度",
    "features.card7.title": "多客户工作区",
    "features.card7.desc": "管理多个客户而不混淆对话或文件。",
    "features.card7.bullet1": "有序的流程",
    "features.card7.bullet2": "更好的跟进纪律",
    "features.card7.bullet3": "专为独立代理和小团队设计",
    "features.card8.title": "机构网站/落地页构建器（专业版）",
    "features.card8.desc": "专业地展示您的机构并捕获入站潜在客户。",
    "features.card8.bullet1": "简单的网站块",
    "features.card8.bullet2": "品牌就绪的展示",
    "features.card8.bullet3": "将潜在客户连接到您的门户工作流程",

    "solution.title": "SourSync 之后的生活",
    "solution.text_rotate": "简化,流程化,成功导向",
    "solution.before.title": "挣扎",
    "solution.before.item1": "太多应用程序和工具",
    "solution.before.item2": "耗时的手动报价",
    "solution.before.item3": "沟通混乱 (WeChat, WhatsApp)",
    "solution.before.item4": "电子表格错误和数据丢失",
    "solution.after.title": "解决方案",
    "solution.after.item1": "一体化采购仪表板",
    "solution.after.item2": "即时报价生成器",
    "solution.after.item3": "客户和订单的实时跟踪",
    "solution.after.item4": "集成沟通中心",

    "pricing.title": "简单透明的定价",
    "pricing.subtitle": "选择适合您需求的计划。",
    "pricing.monthly": "月付",
    "pricing.yearly": "年付",
    "pricing.compare_title": "比较计划",
    "pricing.compare_subtitle": "详细功能比较",
    "pricing.plan.starter.name": "入门版",
    "pricing.plan.starter.desc": "适合个人代理、自由职业者、初学者。",
    "pricing.plan.starter.cta": "加入候补名单",
    "pricing.plan.growth.name": "成长版",
    "pricing.plan.growth.desc": "最适合管理更多客户和频繁发货的活跃代理。",
    "pricing.plan.growth.cta": "加入候补名单",
    "pricing.plan.pro.name": "专业版",
    "pricing.plan.pro.desc": "最适合希望获得更强品牌体验和可扩展运营的机构。",
    "pricing.plan.pro.cta": "加入候补名单",
    "pricing.table.feature": "功能",
    "pricing.table.starter": "入门版",
    "pricing.table.pro": "专业版",
    "pricing.table.agency": "机构版",
    "pricing.table.enterprise": "企业版",

    "faq.title": "常见问题",
    "faq.subtitle": "关于 SourSync 您需要知道的一切。",
    "faq.q1": "什么是 SourSync？",
    "faq.a1": "SourSync 是一款一体化采购代理软件，可帮助您在一个系统中管理客户询价、产品采购、报价、订单、运输和付款，并提供专业的客户门户。",
    "faq.q2": "谁应该使用 SourSync？",
    "faq.a2": "SourSync 专为中国采购代理、进出口代理、贸易公司和希望用结构化仪表板和面向客户的门户替代 WhatsApp + Excel 的小团队而构建。",
    "faq.q3": "SourSync 如何帮助采购代理？",
    "faq.a3": "SourSync 通过集中管理报价、订单状态更新、运输跟踪、付款跟踪和客户沟通历史来减少来回沟通。这提高了信任度，加快了决策速度，并帮助您达成更多交易。",
    "faq.q4": "SourSync 是否包含客户门户？",
    "faq.a4": "是的。每个客户都可以安全登录采购代理的客户门户，在那里他们可以查看报价、订单进度、运输更新和付款状态。",
    "faq.q5": "客户可以在 SourSync 内批准报价吗？",
    "faq.a5": "是的。SourSync 支持清晰的报价工作流程，客户可以审查和确认报价，减少延误和误解。",
    "faq.q6": "SourSync 适合独立采购代理吗？",
    "faq.a6": "是的。SourSync 专为希望简单设置和看起来像大型运营的专业系统的独立创始人和小机构而设计。",
    "faq.q7": "我可以同时管理多个客户和订单吗？",
    "faq.a7": "是的。SourSync 专为多客户运营而设计，允许您跟踪多个报价、订单和运输，而不会混淆数据。",
    "faq.q8": "SourSync 支持订单管理吗？",
    "faq.a8": "是的。SourSync 作为采购代理的订单管理系统，让您在一个地方跟踪订单阶段、供应商详情、时间表和客户更新。",
    "faq.q9": "SourSync 提供运输跟踪吗？",
    "faq.a9": "是的。您可以更新运输阶段并共享跟踪信息，使 SourSync 成为进出口工作流程的实用运输跟踪工具。",
    "faq.q10": "我可以跟踪付款和余额吗？",
    "faq.a10": "是的。SourSync 为采购代理提供结构化的付款跟踪，因此您可以记录每笔订单的押金、剩余余额和付款里程碑。",
    "faq.q11": "SourSync 可以替代 WhatsApp 吗？",
    "faq.a11": "SourSync 不会强迫您停止使用 WhatsApp。相反，它成为您用于报价、订单、运输和付款的官方系统，而 WhatsApp 仍然是沟通渠道。",
    "faq.q12": "SourSync 是否为代理提供网站或落地页构建器？",
    "faq.a12": "是的。SourSync 可以包括一个简单的网站/落地页构建器，供采购机构使用，允许您展示服务、捕获潜在客户并将客户连接到您的门户。",
    "faq.q13": "我可以在 SourSync 中使用自己的域名吗？",
    "faq.a13": "是的。使用支持的计划，您可以为您的机构网站和客户门户连接自定义域名，以增强您的品牌可信度。",
    "faq.q14": "我的客户数据安全吗？",
    "faq.a14": "是的。SourSync 使用现代身份验证和访问控制，因此每个客户只能看到自己的数据，支持安全的多客户 SaaS 工作流程。",
    "faq.q15": "我可以多快开始使用 SourSync？",
    "faq.a15": "大多数代理可以在同一天快速设置他们的工作区并开始共享报价和客户访问。",
    "faq.q16": "接受哪些付款方式？",
    "faq.a16": "我们接受所有主要信用卡、PayPal 和企业计划的银行转账。",
    "faq.more_questions": "还有问题吗？",
    "faq.contact_support": "联系支持",

    "footer.rights": "版权所有。",
    "footer.terms": "服务条款",
    "footer.privacy": "隐私政策",
    "cta.title": "准备好简化您的采购业务了吗？",
    "cta.subtitle": "加入候补名单，成为首批在发布时访问 SourSync 的用户。",
    "cta.email_placeholder": "输入您的邮箱",
    "cta.join_waitlist": "加入候补名单",
    "cta.submitting": "提交中...",
    "cta.success_message": "您已加入列表！我们将在发布时通知您。",
    "cta.note": "早期访问 • 优先支持 • 独家更新",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Detect browser language on initial load
    const browserLang = navigator.language.split('-')[0] as Language;
    if (['en', 'fr', 'ar', 'zh'].includes(browserLang)) {
      setLanguage(browserLang);
    }
  }, []);

  useEffect(() => {
    // Update text direction for Arabic
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.body.setAttribute('data-lang', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
